### ISSUE TITLE
大部分历史记录并未记录

### ISSUE THREAD

**Issue by jiang-yuan** [maoSting/zhihu#3]
win11 edge
每天也会看几条知乎吧,一起也几十条了
历史记录插件里只记录了寥寥几条,而且都是一两周之前的
![Snipaste_2022-04-14_01-57-22](https://user-images.githubusercontent.com/36291537/163241644-65470041-f9dc-42fa-a668-aa0585d6ae65.png)

**Comment by maoSting** [comment]
该助手仅仅会记录【首页】- 【关注/推荐】- 【阅读全文】按钮产生的浏览记录（该浏览不会产生浏览历史），正常打开tab会有浏览器历史记录记录

**Comment by jiang-yuan** [comment]
是点击首页的阅读全文,不是点开新tab,但并未记录

**Comment by maoSting** [comment]
加了一个issues模板，按照那个填写一下，现在的信息不足以判断是什么情况

**Comment by jiang-yuan** [comment]
> 加了一个issues模板，按照那个填写一下，现在的信息不足以判断是什么情况

刚才试了下又能记录了，不知道是不是更新了新版的原因
如果之后有问题我再submit issue
