### ISSUE TITLE
首页点击回答文字而不是‘阅读全文’按钮不记录

### ISSUE THREAD

**Issue by jiang-yuan** [maoSting/zhihu#5]
**操作系统**
windows

**chrome 版本**
Microsoft Edge
版本 101.0.1210.39

**问题描述**
![Snipaste_2022-05-10_06-54-15](https://user-images.githubusercontent.com/36291537/167511750-a229a920-9668-4186-8e18-d7efa5d213c9.png)
上图为历史助手记录的阅读全文按钮点击展开后的回答
![Snipaste_2022-05-10_06-55-24](https://user-images.githubusercontent.com/36291537/167511764-8d70bbde-5647-4e2a-a90f-3685309b389b.png)
下图为浏览器历史记录中打开首页的天数，浏览器搜索历史记录会合并同一天的记录，假设每天打开3次，每次平均在首页点击展开两条，至少每天应该有5条以上在首页的展开回答

今天经过测试发现，因为我个人展开回答是直接点击折叠的回答文字而不是'阅读全文'按钮，所以未记录。但是日常习惯来说很多人就是直接点击文字展开而不是专门去找阅读全文按钮来点击的，希望可以加上点击折叠文字也同样可以记录的功能。

**Comment by maoSting** [comment]
已经收到，晚一点时间我会复现一下，进行修复。

**Comment by jiangmos** [comment]
手动把本地 \apps\content\contentScript.js 中的绑定改为父div 实现了点击记录
但是出现了重复记录的情况   添加了一个乐观锁之后发现 知乎的div展开和收缩是会刷掉乐观锁的记录标志   所以会导致第一次点击记录并且展开  第二次点击重复记录。前端代码不精  期待解决

**Comment by maoSting** [comment]
修改了事件的绑定对象，已经能点击全部。

**Comment by jiang-yuan** [comment]
可以了,辛苦
