### ISSUE TITLE
希望能添加对最新版edge的支持

### ISSUE THREAD

**Issue by isCopyman** [maoSting/zhihu#6]
**操作系统**
mac / windows / linux
win10
**chrome 版本**
这个很重要，要填写
microsoft edge 能装上但是不能用，希望能添加edge的支持
**问题描述**
详细的描述一下问题，或者复现步骤。

**Comment by maoSting** [comment]
https://github.com/maoSting/zhihu/issues/5，你可以该用户交流一下。他也是用的edge

**Comment by isCopyman** [comment]
> [https://github.com/maoSting/zhihu/issues/5，你可以该用户交流一下。他也是用的edge](https://github.com/maoSting/zhihu/issues/5%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E8%AF%A5%E7%94%A8%E6%88%B7%E4%BA%A4%E6%B5%81%E4%B8%80%E4%B8%8B%E3%80%82%E4%BB%96%E4%B9%9F%E6%98%AF%E7%94%A8%E7%9A%84edge)

已经更新版本了吗
